<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.maydear</groupId>
        <artifactId>flyway-database-support</artifactId>
        <version>13.4.0-SNAPSHOT</version>
    </parent>
    <artifactId>flyway-database-dm8</artifactId>
    <packaging>jar</packaging>

    <name>flyway-database-dm8</name>
    <description>Flyway database support for DaMeng Database (DM8, 达梦数据库).</description>
    <url>https://github.com/maydear</url>
    <scm>
        <url>${project.url}</url>
        <connection>scm:git:${project.url}/flyway-database-support.git</connection>
        <developerConnection>scm:git:${project.url}/flyway-database-support.git</developerConnection>
    </scm>
    <issueManagement>
        <system>GitHub</system>
        <url>${project.url}/flyway-database-support/issues</url>
    </issueManagement>

    <developers>
        <developer>
            <name>kelvin</name>
            <organization>Maydear</organization>
            <organizationUrl>${project.url}</organizationUrl>
            <url>${project.url}</url>
        </developer>
    </developers>

    <dependencies>
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-core</artifactId>
        </dependency>

        <dependency>
            <groupId>com.dameng</groupId>
            <artifactId>DmJdbcDriver11</artifactId>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
